apiVersion: v1
kind: Service
metadata:
  name: {{ include "server-print.fullname" . }}
  labels:
    {{- include "server-print.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 30007
      name: http
  selector:
    {{- include "server-print.selectorLabels" . | nindent 4 }}
