apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: server-print-release
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: server-print
      version: '0.0.1'
      sourceRef:
        kind: HelmRepository
        name: flux-test-project-helm-registry
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
