# Git Repo & Secret
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: state-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/CatalinStratulat/FluxTests
  ref:
    branch: main
  secretRef:
    name: flux-gitrepo-secret

---
apiVersion: v1
data:
  password: Z2hwX21LTkxCTzhMM2xCdjNEb0Q5SXBCOEtENVRKMkJhSDJlQWF5bg==
  username: Q2F0YWxpblN0cmF0dWxhdA==
kind: Secret
metadata:
  namespace: flux-system
  name: flux-gitrepo-secret
type: Opaque

---
# Helm Repo

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flux-test-project-helm-registry
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://catalinstratulat.github.io/FluxTestProject/
---
# Kustomization

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kz
  namespace: flux-system
spec:
  force: true
  interval: 1m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: state-repo
  targetNamespace: flux-system
